Service event logging service
andrejn-ct/kapua pull request #2
Opened 2018-07-10 08:20 UTC by andrejn-ct

A new logging service is implemented. It listens to all the service events and logs them into a database.
At the moment no cleanup is in place, meaning that the table containing the log entries just grows. Some way to manually delete the entries would be needed. Perhaps some sort of housecleaning with a dedicated time-to-live parameter for the logging service.

2018-07-10 14:59 UTC, Coduz requested changes
Hi Andrej, 

I've made a quick code review. 
There are some things to change. 
Then I'll also try to test, if required.

Regards, 

_Alberto_

2018-07-10 14:59 UTC, Coduz commented on service/eventlog/api/src/main/java/org/eclipse/kapua/service/eventlog/EventLog.java
> +    @XmlElement(name = "entityScopeId")
This is missing `@XmlJavaTypeAdapter(KapuaIdAdapter.class)`

2018-07-10 14:59 UTC, Coduz commented on service/eventlog/api/src/main/java/org/eclipse/kapua/service/eventlog/EventLog.java
> +    KapuaId getEntityId();
@XmlJavaTypeAdapter(KapuaIdAdapter.class)

2018-07-10 14:59 UTC, Coduz commented on service/eventlog/api/src/main/java/org/eclipse/kapua/service/eventlog/EventLogCreator.java
> +    KapuaId getEntityScopeId();
@XmlJavaTypeAdapter(KapuaIdAdapter.class)

2018-07-10 14:59 UTC, Coduz commented on service/eventlog/api/src/main/java/org/eclipse/kapua/service/eventlog/EventLogCreator.java
> +    KapuaId getEntityId();
@XmlJavaTypeAdapter(KapuaIdAdapter.class)

2018-07-10 14:59 UTC, Coduz commented on service/eventlog/internal/src/main/java/org/eclipse/kapua/service/eventlog/internal/EventLogServiceImpl.java
> +            throw new KapuaEntityNotFoundException(eventLog.TYPE, eventLogId);
This will cause a `NullPointerException`. It should be `EventLog.TYPE`

2018-07-10 14:59 UTC, Coduz commented on service/eventlog/internal/src/main/java/org/eclipse/kapua/service/eventlog/internal/EventLogServiceImpl.java
> +        if (kapuaEvent == null) {
`throw` some exception otherwise `logReceivedEvent` will throw a `NullPointerException`

2018-07-10 14:59 UTC, Coduz commented on service/eventlog/internal/src/main/java/org/eclipse/kapua/service/eventlog/internal/EventLogServiceImpl.java
> +        // Argument Validation
On argument validation please remove the `.get()` part form Id checks. 
We check on `.getScopeId` which, when `null`, is an invalid parameter.

2019-02-22 08:52 UTC, closed without merging

2019-02-22 08:52 UTC, andrejn-ct commented
Just a test pull request. Not to be merged.